[build]
  command = "npm start"
  publish = "public"

[build.environment]
  NODE_VERSION = "16"

[context.production]
  command = "npm start"
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  command = "npm start"
  environment = { NODE_ENV = "development" }
